### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by evacchi** [RatulSaha/presento#1]
Hi,

I was trying to the example with XeLaTeX using a minimal MacTeX install, but I'm getting this error

```
No file presento.nav.

! Package PGF Math Error: You've asked me to divide `360' by `0.0', but I canno
t divide any number by `0.0' (in '\c@framenumber *(360/(\c@totalfr -1))').

See the PGF Math package documentation for explanation.
```

~~what should I do ?~~

The culprit is apparently line 53 in `presento.sty`

``` tex
\filldraw[fill=colorblue!40, draw=colorblue!50]  (0,0) -- (0.2,0) arc (0:{\value{framenumber}*(360/(\value{totalfr}-1))}:0.2) -- (0,0); 
```

which should read (I guess):

``` tex
\filldraw[fill=colorblue!40, draw=colorblue!50]  (0,0) -- (0.2,0) arc (0:{\value{framenumber}*(360/(\value{totalfr}))}:0.2) -- (0,0); 
```

notice **\value{totalfr}-1** becomes **\value{totalfr}**

**Comment by RatulSaha** [comment]
Thanks for the edit. I have fixed the issue following LianTze Lim's edit at [overleaf](https://www.overleaf.com/latex/templates/presento-beamer-theme/knsxtwmfpttq).
