### ISSUE TITLE
Cannot create slide decks with more than 45 slides

### ISSUE THREAD

**Issue by jsta** [RatulSaha/presento#11]
I believe there is an issue with the counter math throwing an error when the deck has more than 45 slides:

>! Dimension too large. <recently
read> \pgfmath@x

See https://tex.stackexchange.com/a/284780/52459

**Comment by RatulSaha** [comment]
Interesting, didn't know that. Would you mind opening a PR?

**Comment by RatulSaha** [comment]
https://github.com/RatulSaha/presento/pull/12
