### ISSUE TITLE
No .tex file for other demo?

### ISSUE THREAD

**Issue by lazysquid** [RatulSaha/presento#3]
Hello. 

I'm starting to use Beamer and LaTeX and decided your template as my standard template for beamer.

I understood your codes and how it flows.

But the problem is I have almost no knowledge of LaTeX so I have zero idea how to transform your minimal demo into these awesome presentation slides. 
e.g. you drew a lot of diagrams and tree structures. I have no idea that it is actual imported image files or generated from LaTeX code.
e.g. arrows pointing contents. It could be LaTeX command, It could be image or It could be generated image using vector drawing command in LaTeX. 

https://github.com/RatulSaha/presento/blob/master/demo/setta_presentation.pdf
https://github.com/RatulSaha/presento/blob/master/demo/BoS_final_presentation.pdf

It could be rude but if you don't mind, could you provide samples of your other demo or give me some hints? such as name of command or packages..

It would make my life much easier. Otherwise I should search everything from bottom cause I have almost no knowledge of LaTeX.

Wonjun

**Comment by RatulSaha** [comment]
Some figures are made using tikz, a latex package for drawing, and some are direct images. You may find a lot of examples and how-to around internet about tikz (e.g. https://www.overleaf.com/help/95-how-to-draw-diagrams-using-the-tikz-package) and how to include images.

Do let me know if there is any specific issue with the template.

**Comment by lazysquid** [comment]
Thanks. 

These are lists of my dumb questions.

https://github.com/RatulSaha/presento/blob/master/demo/setta_presentation.pdf
page 1 : How to make letters in blue box at the very beginning of the page.
page 2 : How to make arrows pointing right side at each of rows?

https://github.com/RatulSaha/presento/blob/master/demo/BoS_final_presentation.pdf
Page 6 : How to place character images as you want. More specifically, it looks like you managed multiple images and placed them as you want. Is it done by tikz?.
Page 6 : How did you draw two blue arrows pointing images? Is it done by tikz?.

Probably most of these questions would be resolved after I memorize all packages and commands in LaTeX. But well.. LaTeX is huge program and I don't know where/how to start it. Probably your answers and template will help me a lot.

Sorry for bothering you.

**Comment by RatulSaha** [comment]
Answer 1:

```
\newcommand{\myTitle}{{\color{colorblue}\largetext{\tikz[overlay,remember picture,baseline=0.3em]{\fill[fill=colorblue]  (-1.3,-0.05) rectangle (8.7,0.9); }\latolightfont\color{colororange}~~{\color{white}\hspace*{-2mm}Quantitative Model Checking of}}\linebreak\vspace*{-.5cm} \hugetext{Resource-constrained Business Processes}}}
```

Answer 2: https://github.com/RatulSaha/presento#how-do-i-add-bullet-points-to-items-in-baseitemize-of-fullpageitemize

Answer 3 and 4: tikz, yes.

It takes some time to learn tikz, it can't happen overnight. Start with basic shapes and most importantly, what you want to build (a small parts of that, maybe). You do not have to remember "all packages and commands".
