### ISSUE TITLE
Itemize, \titlegraphics{}

### ISSUE THREAD

**Issue by andrisecker** [RatulSaha/presento#5]
Hi,
I love the template !

2 quick question:
1) How do you create the arrows for item in itemize environment (see examples without .tex file...)? I tried to set it to circle with this: \setbeamertemplate{itemize items}[circle] and it's not working.
2) Is there any hope to fix \titlegraphics{} and add logo to the titlepage?

Thanks,
András

**Comment by RatulSaha** [comment]
Hello,

Thanks.

1. https://github.com/RatulSaha/presento#how-do-i-add-bullet-points-to-items-in-baseitemize-of-fullpageitemize
2. Try editing this maybe? https://github.com/RatulSaha/presento/blob/master/config/presento-config.tex

Please close the issue if it resolves your query.

**Comment by andrisecker** [comment]
Thanks, and also thanks for the awesome speed!

**Comment by RatulSaha** [comment]
No problem. Closing the issue.
